name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t hashith/vojo_admin_front  .
      - name: Publish Image to docker hub
        run: docker push hashith/vojo_admin_front:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Login to docker hub
        run: sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull image from docker hub
        run: sudo docker pull hashith/vojo_admin_front:latest
      - name: Delete old container
        run: sudo docker rm -f react-container
      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name react-container hashith/vojo_admin_front:latest
